= Yam Master's Backend
Clément LAFON
v0.3
:toc:
:hide-uri-scheme:

This code is part of a bigger project that makes an application to play the Yam Master.

== Technical Stack

== Requirements 

- Bun >= 1.1.6 (https://bun.sh/docs/installation)

== Why rewrite?

I rewrote the base written by Julien simply to reappropriate myself the code, understand it more finely and challenge myself on an aspect that interested me, trying out Typescript.

This work is not intended to simplify or improve the 'code quality' of what has already been done.
It will therefore be a mix of OOP and procedural programming.

For simplicity's sake, there will be no methods for all possible class actions, and some properties will be directly public for direct access.

== Features

== Environment Variables

This feature needs for the server to run with *Bun*.
If not you will have to install the *dotenv* package and import it on the `index.js`.

You can activate the dev features of the backend by setting this variable to "dev".

[horizontal]
`ENVIRONMENT`::
- "dev" (development)
- "" (production)

== Run locally

1.

== Deployment

1.

== Class Diagram

image::https://www.plantuml.com/plantuml/png/JSqn2W9138NX_fqYjR0Ni5fGs5RG2mpPXmGpgsHc2n7lBiR2RGBV8_2FhPVeQtL0lRGcH-fDNX1v69LDzc9BvvM1Dp2LIjaDWroiCluyUNbkFOND-9xKWUx0xoU7izw3co6ZGAQJfiJ8PLwhVm00[]

